pin psycopg2==2.6.1 and sqlalchemy==1.0.13
This is to avoid an error we're seeing very often in the logs:

OperationalError: (psycopg2.OperationalError) SSL connection has been
closed unexpectedly

We do not see this error on chacra.ceph.com which has these versions,
but we do see it on 1.chacra.ceph.com which had 2.6.2 for psycopg2.

Signed-off-by: Andrew Schoen <aschoen@redhat.com>